server:
  port: 8083

spring:
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb://localhost:27017/proxymelidb
  cloud:
    gateway:
      routes:
        - id: meli-proxy
          uri: https://api.mercadolibre.com
          predicates:
            - Path=/**

rate-limiter:
  defaults:
    replenishRate: 1000
    burstCapacity: 1000
  rules:
    - path: /categories/
      replenishRate: 10000
      burstCapacity: 10000
    - path: /items/
      ip: 152.152.152.152
      replenishRate: 10
      burstCapacity: 10
    - ip: 152.152.152.152
      replenishRate: 1000
      burstCapacity: 1000
    - ip: 152.152.152.152
      replenishRate: 1
      burstCapacity: 1

resilience4j.circuitbreaker:
  instances:
    meliBackend:
      slidingWindowSize: 10
      failureRateThreshold: 50
      slowCallDurationThreshold: 2s
      slowCallRateThreshold: 100
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    export:
      prometheus:
        enabled: true
