apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: meli
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'proxy-meli'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['proxy.meli.svc.cluster.local:8080']
      - job_name: 'redis'
        static_configs:
          - targets: ['redis-exporter.meli.svc.cluster.local:9121']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.meli.svc.cluster.local:9100']
