server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/proxymelidb

resilience4j.circuitbreaker:
  instances:
    meliBackend:
      slidingWindowSize: 10
      failureRateThreshold: 50
      slowCallDurationThreshold: 2s
      slowCallRateThreshold: 100
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3